name = "cfparrav-song-suggestions"
main = "worker.js"
compatibility_date = "2026-08-14"
preview_urls = false

kv_namespaces = [
  { binding = "SUGGESTIONS", id = "ee7882905787475b91714b7f0c3318ec" }
]

[observability]
enabled = true

[observability.logs]
enabled = true
